package com.sem2.FurnitureCompany.Enums;

public enum OrderState {
    PENDING, PREPARING_MATERIAL, BEING_CUT, WAITING_FOR_VARNISH, BEING_VARNISHED, WAITING_FOR_ASSEMBLY, BEING_ASSEMBLED, ASSEMBLED, WAITING_FOR_FITTING, BEING_FITTED,
    FINISHED
}
